config/routes.rb
Rails.application.routes.draw do
  post 'users/set_current_user', to: 'users#set_current_user', as: 'set_current_user'

  resources :artworks
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "artworks#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/artwork.rb
class Artwork < HerModel
  include Filterable
  belongs_to :user

  scope :filter_by_user_id, ->(user_id) { where(user_id: user_id) }
  scope :filter_by_movement, ->(movement) { where(movement: movement) }
end

app/models/concerns/filterable.rb
# frozen_string_literal: true

# Filterable concern
module Filterable
  extend ActiveSupport::Concern

  # Adds class methods to the including class
  class_methods do
    def filter(filtering_params)
      results = all
      filtering_params.each do |key, value|
        results = results.public_send("filter_by_#{key}", value) if value.present?
      end
      results
    end
  end
end

app/models/her_model.rb
class HerModel
  include Her::Model
  scope :by_page, ->(page) { where(page: page) }

  # Parsing options
  # parse_root_in_json true
  # include_root_in_json true

  # Add ActiveRecord style update
  def update(attributes = {})
    attributes.each do |key, value|
      send("#{key}=", value)
    end
    save
  end
end

app/models/user.rb
class User < HerModel
  has_many :artworks

  def self.users_collection
    all.uniq.map { |user| [user.first_name, user.id] }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :current_user

  def current_user
    @current_user = Thread.current[:user]
  end
end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController
  before_action :set_artwork, only: %i[ show edit update destroy ]

  # GET /artworks or /artworks.json
  def index
    @artworks = Artwork.all
    @artworks = Artwork.filter(filter_params) if filter_params.present?
    @users = User.all
    @pagy = Pagy.new @artworks.metadata
  end

  # GET /artworks/1 or /artworks/1.json
  def show
  end

  # GET /artworks/new
  def new
    @artwork = Artwork.new
  end

  # GET /artworks/1/edit
  def edit
  end

  # POST /artworks or /artworks.json
  def create
    @artwork = Artwork.new(artwork_params)

    respond_to do |format|
      if @artwork.save
        format.html { redirect_to artwork_url(@artwork), notice: "Artwork was successfully created." }
        format.json { render :show, status: :created, location: @artwork }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @artwork.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artworks/1 or /artworks/1.json
  def update
    respond_to do |format|
      if @artwork.update(artwork_params)
        format.html { redirect_to artwork_url(@artwork), notice: "Artwork was successfully updated." }
        format.json { render :show, status: :ok, location: @artwork }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @artwork.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artworks/1 or /artworks/1.json
  def destroy
    @artwork.destroy

    respond_to do |format|
      format.html { redirect_to artworks_url, notice: "Artwork was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artwork
      @artwork = Artwork.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def artwork_params
      params.require(:artwork).permit(:user_id, :title, :description, :movement, :price)
    end

    def filter_params
      # TODO: needs refactor
      if params[:user_id].present?
        params[:user_id] = [params[:user_id]].flatten
        @user_id = params[:user_id]&.map(&:to_s)
      end

      if params[:movement].present?
        params[:movement] = [params[:movement].split(',')].flatten
        @movement = params[:movement].join(',')
      end
  
      params.permit(:title, :price_min, :price_max, user_id: [], movement: [])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
    @users = User.by_page(params[:page]) if params[:page].present?
    @pagy = Pagy.new @users.metadata
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def set_current_user
    Thread.current[:user] = User.find(params[:current_user_id])
    redirect_to root_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/views/artworks/_artwork.html.erb
<div id="<%= dom_id artwork %>">
  <p>
    <strong>User:</strong>
    <%= "#{artwork.user_id} - #{artwork.user.first_name} #{artwork.user.last_name}" %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= artwork.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= artwork.description %>
  </p>

  <p>
    <strong>Movement:</strong>
    <%= artwork.movement %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= artwork.price %>
  </p>

</div>

app/views/artworks/_form.html.erb
<%= form_with(model: artwork) do |form| %>
  <% if artwork.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(artwork.errors.count, "error") %> prohibited this artwork from being saved:</h2>

      <ul>
        <% artwork.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :movement, style: "display: block" %>
    <%= form.text_field :movement %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/artworks/edit.html.erb
<h1>Editing artwork</h1>

<%= render "form", artwork: @artwork %>

<br>

<div>
  <%= link_to "Show this artwork", @artwork %> |
  <%= link_to "Back to artworks", artworks_path %>
</div>

app/views/artworks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Artworks</h1>

<%= form_with url: artworks_path, method: :get do | form | %>

  <div class="form-group">
    <%= form.label :movement %>
    <%= form.text_field :movement, value: @movement, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :user_id, class: "form-label select-label"%>
    <%= select_tag :user_id, options_from_collection_for_select(@users, :id, :first_name, @user_id), multiple: true, class: 'form-control select-control'%>
  </div>

  <div class="form-group m-3">
    <%= form.submit "Search", class: "btn btn-primary" %>
    <%= link_to "Clear", artworks_path, class: "btn btn-primary" %>
    <%= link_to "New artwork", new_artwork_path, class: "btn btn-primary"  %>
  </div>
<% end %>

<%== pagy_nav(@pagy) %>

<div id="artworks" class="row">
  <% @artworks.each do |artwork| %>
    <div class="card m-2" style="width: 18rem;">
      <div class="m-3">
        <%= render artwork %>
        <p>
          <%= link_to "Show this artwork", artwork %>
        </p>
      </div>
    </div>
  <% end %>
</div>

app/views/artworks/new.html.erb
<h1>New artwork</h1>

<%= render "form", artwork: @artwork %>

<br>

<div>
  <%= link_to "Back to artworks", artworks_path %>
</div>

app/views/artworks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @artwork %>

<div>
  <%= link_to "Edit this artwork", edit_artwork_path(@artwork) %> |
  <%= link_to "Back to artworks", artworks_path %>

  <%= button_to "Destroy this artwork", @artwork, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </head>

  <body>
    <div class='container'>
      <%= render 'users/set_user_form'  %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_set_user_form.html.erb
<%= form_with url: set_current_user_path, method: :post do | form | %>
  <div class="form-group">
    <%= form.label :current_user_id, 'Current user session: ', class: "form-label select-label"%>
    <%= "#{@current_user&.id} - #{@current_user&.first_name} #{@current_user&.last_name}"  %>
    <%= form.select(:current_user_id, User.users_collection, {include_blank: true, selected: @current_user&.id }, class: 'form-control select-control')%>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>First name:</strong>
    <%= user.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= user.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>
<%= link_to "New user", new_user_path %>
<%== pagy_nav(@pagy) %>

<div id="users" class="row">
  <% @users.each do |user| %>
    <div class="card m-2" style="width: 18rem;">
      <div class="m-3">
        <%= render user %>
        <p>
          <%= link_to "Show this user", user %>
        </p>
      </div>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>